import modelImg from '../assets/img/cars/bmw-5-series-black.png';
import modelImg2 from '../assets/img/cars/bmw-small-2.png';
import modelImg3 from '../assets/img/cars/bmw-small-white.png';
import modelImg4 from '../assets/img/cars/bmw-small-3s.png';

const CARS = [
  {
    id: 120,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'blue',
    salon: 'leather',
    fuel: 'diesel',
    engine: '3.0',
    popular: true,
    price: '50 000$',
    img: modelImg,
  },
  {
    id: 121,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'white',
    salon: 'leather',
    fuel: 'petrol',
    engine: '3.0',
    popular: true,
    price: '55 000$',
    img: modelImg3,
  },
  {
    id: 122,
    name: 'BMW X6',
    transmission: 'automatic',
    color: 'brown',
    salon: 'leather',
    fuel: 'petrol',
    engine: '2.5',
    popular: true,
    price: '75 000$',
    img: modelImg2,
  },
  {
    id: 123,
    name: 'BMW 3 Series',
    transmission: 'automatic',
    color: 'white',
    salon: 'leather',
    fuel: 'diesel',
    engine: '2.0',
    popular: true,
    price: '35 000$',
    img: modelImg4,
  },
  {
    id: 124,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'blue',
    salon: 'leather',
    fuel: 'diesel',
    engine: '3.0',
    popular: false,
    price: '50 000$',
    img: modelImg,
  },
  {
    id: 125,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'blue',
    salon: 'leather',
    fuel: 'diesel',
    engine: '3.0',
    popular: false,
    price: '50 000$',
    img: modelImg,
  },
  {
    id: 126,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'blue',
    salon: 'leather',
    fuel: 'diesel',
    engine: '3.0',
    popular: false,
    price: '50 000$',
    img: modelImg,
  },
  {
    id: 127,
    name: 'BMW 5 Series',
    transmission: 'automatic',
    color: 'blue',
    salon: 'leather',
    fuel: 'diesel',
    engine: '3.0',
    popular: false,
    price: '50 000$',
    img: modelImg,
  },
];

export default CARS;
